// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package grpc;

public interface GrpcRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GrpcRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string drug = 1;</code>
   * @return The drug.
   */
  String getDrug();
  /**
   * <code>string drug = 1;</code>
   * @return The bytes for drug.
   */
  com.google.protobuf.ByteString
      getDrugBytes();
}
